name: authentication_repository
description: Dart package which manages the authentication domain. written from https://bloclibrary.dev/#/flutterlogintutorial as tutorial
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  very_good_analysis: ^3.1.0
